---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: {{ include "odoo.ns" . }}
  labels:
    app: odoo
    component: web
data:
{{- range $key, $value := .Values.odoo.config }}
{{- if contains "\n" (toString $value) }}
  {{ $key }}: |
{{ $value | indent 4 }}
{{- else }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
