---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace.name }}
  labels:
    app: odoo
    component: database
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: odoo
    component: database
