---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-db-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: odoo
    component: database
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
